apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-data-pvc
  namespace: monitoring
  labels:
    app: prometheus
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 1Gi
