apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      env: monitoring
      app: prometheus
  template:
     metadata:
       name: prometheus
       labels:
         env: monitoring
         app: prometheus
     spec:
       containers:
         - name: prometheus
           image: prom/prometheus
           volumeMounts:
             - name: prometheus-config-map
               mountPath: /etc/prometheus
             - name: prometheus-volume
               mountPath: /etc/prometheus/data
       volumes:
         - name: prometheus-config-map
           configMap:
             name: prometheus-config-map
         - name: prometheus-volume
           persistentVolumeClaim:
              claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
   - port: 9090
     targetPort: 9090